### ISSUE TITLE
Database not created

### ISSUE THREAD

**Issue by seidler2547** [bvcms/bvcms#450]
I have cloned bvcms and running it on Windows 10 with SQL Express. The problem is that the database is not created. I have checked the connection strings and they seem correct (`.\SQLEXPRESS`). I can connect to the database using Visual Studio. When the database does not exist, I get an error page "Database does not exist: demo" (host=demo). When I do `CREATE DATABASE CMS_demo` beforehand, I get an error trace concerning `dbo.Setting` - which seems to indicate that that bvcms can connect to the database, but then does not find the table "Setting" (because the database structure has not been initialized). I have adjusted `web.config` and also `ConnectionStrings.config` to use `.\SQLEXPRESS`.

**Comment by brondavies** [comment]
Delete the created database and run this SQL statement before starting the project again.   `EXEC sp_configure 'clr strict security', 0; RECONFIGURE;`

**Comment by davidcarroll** [comment]
@brondavies There is another problem related to this. The database is not being created because CreateDatabase is never being called in Global.aspx. This is because in ConnectionStrings.config, the connection string has Data Source="(local)" and he is using ".\SqlExress".

See https://github.com/bvcms/bvcms/blob/a3a244d2df779c91d3b3f55a61ed61405609e3e2/CmsWeb/ConnectionStrings.config#L2

That connection string used to be `<add name="CMS" connectionString="Integrated Security=True" />`.
This change was made recently. It is the absence of a Data Source that allows you to specify the DbServer in web.config. Put that back like it was and it will work.

The `clr strict security` is something you will need to address with a certificate since this is something new in SQL Server. This will be necessary because of supporting open source users to be able to install without this trouble

Also, even if he gets the database built successfully, it will run into an error related to the other two issues I posted here (trying to connect to localhost").

**Comment by seidler2547** [comment]
Well, I got around the first problem - which is Edge. Edge is the default browser in Visual Studio, and it just didn't work. I changed to Internet Explorer and immediately it got further in the process. Then I did the "clr strict security" thing because it told me that. Now I have this problem: https://github.com/bvcms/bvcms/issues/167

I tried a simple `alter database` to change the collation but did threw a bunch of errors, so I might change the `create database` statement.

**Comment by seidler2547** [comment]
Thanks @davidcarroll that indeed was the last step to get it working. Before that I also removed the collation in this SQL file: https://github.com/bvcms/bvcms/blob/a3a244d2df779c91d3b3f55a61ed61405609e3e2/CmsData/Migrations/20181022-2_create_ContributionsTag_table.sql#L7

So to conclude:

- enable TCP protocol in SQL Express Server
- Use IE, not Edge when running from Visual Studio
- adjust `clr strict security` to `0`
- change datasource(s) to `.\SQLEXPRESS` to nothing in `ConnectionStrings.config`
- remove `COLLATE` in mentioned SQL file
- apply @davidcarroll's patch
