### ISSUE TITLE
New Fields for API Person Object

### ISSUE THREAD

**Issue by hkouns** [bvcms/bvcms#59]
I am currently running into "Sql exceptions unhandled by user code" errors (currently says there is an invalid column name ClientIP)  after logging in when running through Visual Studio... and I won't have the time to troubleshoot for a few days... I will likely try reinstalling SQL Express and/or VS next.

In the meantime, I am working on a Python report to be used for verifying a persons contact info and other pertinent data and I wanted to document a couple items I "need".

I would like to have the following fields added to the Person Object API:

Gender
ReceiveSMS
DoNotPublishPhones
MedicalDescription

If someone else gets a chance to add these... please feel free!

**Comment by davidcarroll** [comment]
You need to update your database's schema.

**Comment by hkouns** [comment]
Is this done simply by restoring from the latest backup pulled from Rackspace?  or am I missing a step?

By the way... as of right now, the latest backup appears to be:  Aug 12, 2015 - 3:12 AM EDT
I would have anticipated a file for 13th - 17th as well.  I have not made any changes in the Rackspace control panel...could something have changed on that side?

**Comment by davidcarroll** [comment]
Yes, restoring from back up should do the trick. But it looks like we lost your entry when Mo did some refactoring on the daily backup script file. It was my fault because I failed to check the change in when I originally modified it to include your database. I am going to fix that now and make a backup manually. I'll notify you when that is done. It should resume regularly scheduled backups tonight.

For a church that is using the open source but we are not hosting their database, they would have to build a new database using the source code and then do a dbdiff (https://opendbiff.codeplex.com/) and update their schema from a change script.

**Comment by hkouns** [comment]
Thanks David.

**Comment by davidcarroll** [comment]
Your backup should be out there now and normal operation should resume
tonight

**Comment by hkouns** [comment]
Thanks... the new backup fixed the Issue with my programming environment.
Pull request for new API fields has been merged... Also posted a PR for corresponding API Documentation Changes (https://github.com/bvcms/bvcmsapi/pull/1).  Let me know if that was done correctly.
