### ISSUE TITLE
Report2PDF

### ISSUE THREAD

**Issue by hkouns** [bvcms/bvcms#61]
@davidcarroll, @drmohundro, need your help/thoughts on this commit: https://github.com/GSBCfamily/bvcms/commit/77dd18d8eb98c79a90f9685121e252fcae4555c0

I am working on a feature for converting the output of a python script to PDF.  The idea is that since the output is already HTML, we should be able to parse it with iTextSharp and XMLWorkerHelper and create a PDF that could then be printed or saved.   Do you agree?  Is the XMLWorkerHelper parsing too limited to be useful?  Is this the best tool for this task?

I currently have it parsing the output of simple reports and creating a file locally on the hard drive.  I have not been able to figure out how to make it open the pdf in another window as you typically do for the rollsheet reports, etc.    I have seen your code for using "Response" and HttpContext but I haven't been able to make it work... I think due to my lack of experience with MVC.  Can you point me in the right direction? or point me at documentation to learn how?

The basic version would just be:     *Report2PDF(string report)*
where the python script is ran once and the output is parsed and forms the entire PDF

but it could also be expanded to      *Report2PDF(string report, string query)*
where the Report2PDF function would actually run  the query itself and then call a python script repeatedly for each PID...Each time it calls the script, the formatted output for the new PID would be added as a new page in the PDF.

Long term I would like to find a way to make these custom Reports callable from the Blue Toolbar... (maybe similar to the way you are adding the SQL reports to the toolbar.?)

Do you agree with the general direction of this feature?  suggestions? improvements?  
Thanks for your time and consideration...

**Comment by davidcarroll** [comment]
I have only used the xmlworker class for allowing the user to put some basic header information at the top of contribution statements. I have never used it to create an entire pdf report with. All of the work we have done in iText has been custom crafted reports. I would start with xmlworker and if it is not suitable, switch to building your own tables with iText.

You have to set the correct ContentType on the Response object

            Response.ContentType = "application/pdf";
            Response.AddHeader("content-disposition", "filename=foo.pdf");
Of course the Response object will only be available in the CMSWeb project with an ActionResult method. You would probably want to write the report to the Response.OutputStream instead of creating a string since PDF reports would typically be quite voluminous. This is typically done by inheriting from ActionResult class and overriding the constructor and ExecuteResult methods. This means that you would want your script code to simply run the query and return the DataReader object, then format your report in this ActionResult class in CmsWeb. That is my first blush thoughts. This one would have to be well architected and so don't expect us to accept any pull requests without several rejections and back and forth. Please keep your code isolated in separate code files so there will very little possibility of having to manually merge much.

Also, you can set the target attribute on the anchor element or the form element to "_blank". to get it to open in a new tab.
