### ISSUE TITLE
Null Password Parameter when testing Custom SqlReport

### ISSUE THREAD

**Issue by hkouns** [bvcms/bvcms#67]
I am testing with latest [Codebase](https://github.com/GSBCfamily/bvcms/commit/92615387e874ec10fe66244b3f1a389fc7193616)  and the latest backup of the database (5/30).

I was testing out adding the Custom Sql Report to the blue toolbar...  (using the sample GivingChange code)

Everything works correctly when I test it live online  tpsdb.com, but when I test in my local environment I get the following error screen:

    
    Value cannot be null.
    Parameter name: Password 
    Description: An unhandled exception occurred during the execution of the current web request.     Please review the stack trace for more information about the error and where it originated in the     code. 

    Exception Details: System.ArgumentNullException: Value cannot be null.
    Parameter name: Password

    Source Error: 

    Line 124:            cb.IntegratedSecurity = false;
    Line 125:            cb.UserID = (finance ? $"ro-{cb.InitialCatalog}-finance" : $"ro-{cb.InitialCatalog}");
    Line 126:            cb.Password = ConfigurationManager.AppSettings["readonlypassword"];
    Line 127:            return cb.ConnectionString;
    Line 128:        }  

     Source File:  H:\My Documents\GitHub\bvcms\UtilityExtensions\Extensions\ConnectionStrings.cs    Line:  126 

    Stack Trace: 

Thoughts? of Suggestions on how to debug?

Thanks

**Comment by davidcarroll** [comment]
As you know, an admin user can store both sql and python scripts in their database. These scripts can be executed at run time within the web appliction to effect custom reports and other custom operations. To prevent damage to the database and maintain database integrity, these scripts can only be run in the context of a read only user. The password for these users is in a secrets.config file not in GitHub. 

I have modified the code and pushed a commit so that if that setting does not exist, you can run these scripts with full permissions against a copy of your database. Just keep in mind, that while updates would work in that developer scenario, that is not the intent of the SqlScripts and they would not work on TouchPoint's hosted production server.

**Comment by hkouns** [comment]
Thanks @davidcarroll.  I confirmed that your modification fixed my issue and the SQL Report runs correctly now.

In the past, we have discussed using the offline database backups to verify new SQL scripts... so it caught be off-guard when it wouldn't work.

Please clarify: "*while updates would work in that developer scenario, that is not the intent of the SqlScripts  and they would not work on TouchPoint's hosted production server*"

I was using the same user profile (admin) for the offline testing that I use in the hosted production server...and the sql scripts work correctly on the hosted server.

**Comment by davidcarroll** [comment]
The Database has three users: sa, ro_dbname and ro_dbname_finance. These are not the same as roles or users in the application. The entire application runs using the fully privledged sa account. All protection of the database is governed by what the application allows. When you are using `Admin > Special Content > SQLScript`, you have direct access to the database and if we were to run that using the sa account, you could run updates, delete records and otherwise modify the database without the application knowing it. So we run all SQLScripts in the context of one of the ro accounts, ro standing for read only. Also the contributions table is only accessible to the ro-finance account which allows a Finance role to execute queries against the contributions.

What I have done to make it possible to run those queries in your downloaded database, since you don't have the passwords for the ro users, is to run those queries instead in the sa account. This means that in your development environment, you could actually construct SQL to update the database and delete records etc. that you would not be able to do in the production.

That is what I was refering to when I said *"while updates would work in that developer scenario, that is not the intent of SqlScripts and they would not work on TouchPoint's hosted production server."*

**Comment by hkouns** [comment]
Ahhh... I understand now. Thanks for the clarification.
